---
- name: Include OS-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Ensure munge dependencies are installed
  ansible.builtin.package:
    name:
      - "{{ openssl_libraries }}"
      - "{{ bzip2_libraries }}"
      - "{{ zlib_libraries }}"
      - "{{ package_builder }}"
    state: present

- name: Get munge GitHub page
  ansible.builtin.uri:
    url: https://github.com/dun/munge/releases/latest
    return_content: true
  register: results

- name: Get the name of the latest available munge source archive
  set_fact:
    munge_version: "{{ results.content | split('<title>Release ')
                    | last | split | first }}"

- name: Download munge source
  ansible.builtin.get_url:
    url: "https://github.com/dun/munge/releases/download/
          {{ munge_version }}/{{ munge_version }}.tar.xz"
    dest: /tmp/
    checksum: "sha512:https://github.com/dun/munge/releases/download/
               {{ munge_version }}/{{ munge_version }}.tar.xz.sha512"

- name: Download munge GPG signature
  ansible.builtin.get_url:
    url: "https://github.com/dun/munge/releases/download/
          {{ munge_version }}/{{ munge_version }}.tar.xz.asc"
    dest: /tmp/

- name: Download munge public key
  ansible.builtin.get_url:
    url: "https://github.com/dun.gpg"
    dest: /tmp/

- name: Build munge package
  include_tasks: "build-{{ ansible_os_family }}.yml"
...
