---
- name: Check if the munge binaries already exist
  ansible.builtin.find:
    paths: "/root/rpmbuild/"
    patterns:
      - "munge*.rpm"
    recurse: true
  register: munge_binaries

- name: Build munge RPMs if they have not already been built
  ansible.builtin.command:
    cmd: "{{ rpmbuild_command }} /tmp/{{ munge_version }}.tar.xz"
  when: munge_binaries.files | length != 6
  changed_when: true
...
